### PR TITLE
--update: Using mongoose in-built object id validation.

### PR DESCRIPTION
**Pull request by igauravsehrawat**
I probably should put these kind of validator in `helpers` folder. What say? What should be the file name?

### CODE REVIEW

**Comment by ashokdey** [comment]
@igauravsehrawat: Great first step. Well, I need to see more file changes. use your eagle eye skill to look into more fixes.

**Comment by igauravsehrawat** [comment]
I will move the "fat" function myself.

Thanks

**Comment by igauravsehrawat** [comment]
I am not why Codacy is giving code quality when `airbnb eslint` is passing through.
Two issues [here(https://app.codacy.com/app/ashokdey/node-mongo-rest-api/pullRequest?prid=2134111)
1. Single quote vs double quotes (Airbnb guide: https://github.com/airbnb/javascript#strings--quotes)
2. Arrow-parens (Airbnb guide: https://github.com/airbnb/javascript#arrows--implicit-return, https://github.com/airbnb/javascript#arrows--one-arg-parens)

Thanks

**Comment by ashokdey** [comment]
@igauravsehrawat I am looking into it. Codacy may be messed up. Right now I selected ESLint v4.15.0 with 'Scan config file from project' option for Codacy. Let's wait for it to update.

**Pull request merged**
